apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-frontend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "web-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "web-frontend.name" . }}
    spec:
      containers:
      - name: web-frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}