{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.apiPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api-backend
            port:
              number: {{ .Values.apiBackend.service.port }}
      - path: {{ .Values.ingress.webPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web-frontend
            port:
              number: {{ .Values.webFrontend.service.port }}
{{- end }}