apiBackend:
  image:
    repository: harbor.local/mvp-dev/api-backend
    tag: "0.1"
  service:
    port: 8080

webFrontend:
  image:
    repository: harbor.local/mvp-dev/web-frontend
    tag: "0.1"
  service:
    port: 80

ingress:
  enabled: true
  host: "mvp.local"
  apiPath: "/api"
  webPath: "/"